modLoader="javafml"
loaderVersion="[34,)"
license="GNU General Public License 3"
issueTrackerURL="https://github.com/MrCrayfish/Backpacked/issues"

[[mods]]
modId="backpacked"
version="2.1.13"
displayName="Backpacked"
updateJSONURL="https://mrcrayfish.com/modupdatejson?id=backpacked"
displayURL="https://mrcrayfish.com/mods?id=backpacked"
logoFile="backpacked.png"
authors="MrCrayfish"
credits="JamesTheMaker, Unstellary, and Zinc from Discord for a few backpack ideas."
description="Adds a simple backpack to store more items"

[[dependencies.backpacked]]
    modId="forge"
    mandatory=true
    versionRange="[40.0.32,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.backpacked]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.18.2,1.19)"
    ordering="NONE"
    side="BOTH"
[[dependencies.backpacked]]
    modId="curios"
    mandatory=false
    versionRange="[1.18.2-5.0.6.3,)"
    ordering="AFTER"
    side="BOTH"
[[dependencies.backpacked]]
    modId="controllable"
    mandatory=false
    versionRange="[0.15.1,)"
    ordering="AFTER"
    side="CLIENT"

[modproperties.backpacked]
    catalogueItemIcon="backpacked:backpack" #Support for Catalogue mod
    configuredBackground="minecraft:textures/block/terracotta.png" #Support for Configured mod